name: Test Docker Image

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux environment for Docker

    steps:
      - uses: actions/checkout@v3  # Check out the code
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t cache-warmer .